export enum ITEMS_TO_DELIVER_ACTION_TYPES {
    ITEMS_TO_DELIVER_START = "items-to-deliver/ITEMS_TO_DELIVER_START",
    ITEMS_TO_DELIVER_SUCCESS = "items-to-deliver/ITEMS_TO_DELIVER_SUCCESS",
    ITEMS_TO_DELIVER_FAILED = "items-to-deliver/ITEMS_TO_DELIVER_FAILED",
}


