export enum PRODUCT_ACTION_TYPES  {
    GET_PRODUTC_START = "products/GET_PRODUTC_START",
    GET_PRODUTC_SUCCESS = "products/GET_PRODUTC_SUCCESS",
    GET_PRODUTC_FAILED = "products/GET_PRODUTC_FAILEDi",
}